//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag
    {
        public int id { get; set; }
        public string numero { get; set; }
        public Nullable<int> projetoID { get; set; }
    
        public virtual projeto projeto { get; set; }
    }
}
