//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agEntities : DbContext
    {
        public agEntities()
            : base("name=agEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ag> ags { get; set; }
        public DbSet<projeto> projetoes { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<usuario_has_projeto> usuario_has_projeto { get; set; }
    }
}
