//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_has_projeto
    {
        public int usuario_id { get; set; }
        public int projeto_id { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual projeto projeto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
